name: "Discord"

on:
  release:
    types: [ published ]

jobs:
  notify:
    name: "Notify"
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🎊 New release published: **${{ github.event.release.name }}**

            ${{ github.event.release.html_url }}"
